"""empty message

Revision ID: 0f8bb37feb85
Revises: 55b82c5beea2
Create Date: 2023-05-28 20:26:28.228201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f8bb37feb85'
down_revision = '55b82c5beea2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
