"""empty message

Revision ID: 321fd7c38895
Revises: 647fe445ef78
Create Date: 2023-06-03 12:04:46.589375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '321fd7c38895'
down_revision = '647fe445ef78'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gameranswers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generated_code', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'Asia/Tashkent')"), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gameranswers_generated_code'), 'gameranswers', ['generated_code'], unique=True)
    op.create_index(op.f('ix_gameranswers_id'), 'gameranswers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gameranswers_id'), table_name='gameranswers')
    op.drop_index(op.f('ix_gameranswers_generated_code'), table_name='gameranswers')
    op.drop_table('gameranswers')
    # ### end Alembic commands ###
