"""empty message

Revision ID: 5fb271690bb5
Revises: 30e38d456800
Create Date: 2023-05-28 22:31:59.013674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fb271690bb5'
down_revision = '30e38d456800'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('second', sa.Interval(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'second')
    # ### end Alembic commands ###
