"""empty message

Revision ID: 647fe445ef78
Revises: b70f92fc99e1
Create Date: 2023-05-31 20:05:43.804162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '647fe445ef78'
down_revision = 'b70f92fc99e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activegames', sa.Column('total_gamers', sa.Integer(), nullable=True))
    op.drop_column('activegames', 'total_users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activegames', sa.Column('total_users', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('activegames', 'total_gamers')
    # ### end Alembic commands ###
